### ISSUE TITLE
Not found: ... specs2-mock_3/4.15.0/specs2-mock_3-4.15.0.pom

### ISSUE THREAD

**Issue by mkurz** [etorreborre/specs2#1079]
https://github.com/playframework/play-ws/runs/5885609603?check_suite_focus=true

```
[error] sbt.librarymanagement.ResolveException: Error downloading org.specs2:specs2-mock_3:4.15.0
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.specs2/specs2-mock_3/4.15.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/specs2/specs2-mock_3/4.15.0/specs2-mock_3-4.15.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:3[45](https://github.com/playframework/play-ws/runs/5885609603?check_suite_focus=true#step:5:45))
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:314)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:1[46](https://github.com/playframework/play-ws/runs/5885609603?check_suite_focus=true#step:5:46))
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3690)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:7[48](https://github.com/playframework/play-ws/runs/5885609603?check_suite_focus=true#step:5:48))
[error] (play-ws-standalone / update) sbt.librarymanagement.ResolveException: Error downloading org.specs2:specs2-mock_3:4.15.0
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.specs2/specs2-mock_3/4.15.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/specs2/specs2-mock_3/4.15.0/specs2-mock_3-4.15.0.pom
[error] Total time: 5 s, completed Apr 8, 2022 1:12:29 PM
```

**Comment by etorreborre** [comment]
Yes that's one of the things which have been removed from Scala 3 (I don't remember the exact reason but the mockito support in specs2 was a real hack). The recommendation is to use [ScalaMock](https://scalamock.org/user-guide/sharing-specs2/) now.

**Comment by etorreborre** [comment]
I updated the "cross" notes: https://github.com/etorreborre/specs2/releases/tag/SPECS2-4.13.1-cross with that information

**Comment by mkurz** [comment]
👍
