### ISSUE TITLE
AllExpectations is returning multiple failed expectations, but not the correct failure reports

### ISSUE THREAD

**Issue by jedws** [etorreborre/specs2#320]
import org.specs2.SpecificationWithJUnit
    import org.specs2.specification.AllExpectations

    class MultiExpectSpec extends SpecificationWithJUnit with AllExpectations {
      def is = s2"Testing $test"
      def test = "hello" must have size (10000) and startWith("bell") and ("asd" must beEqualTo("asdd"))
    }

gives:

    java.lang.Exception: 'hello' doesn't have size 10000 but size 5 [TestSpec.scala:10]
    'hello' doesn't have size 10000 but size 5 [TestSpec.scala:10] [TestSpec.scala:10]
    'hello' doesn't have size 10000 but size 5 [TestSpec.scala:10] [TestSpec.scala:10] [TestSpec.scala:10]
      at test.MultiExpectSpec$$anonfun$test$1$$anonfun$apply$1.apply(TestSpec.scala:10)
      at test.MultiExpectSpec$$anonfun$test$1$$anonfun$apply$1.apply(TestSpec.scala:10)
      at test.MultiExpectSpec$$anonfun$test$1.apply(TestSpec.scala:10)
      at test.MultiExpectSpec$$anonfun$test$1.apply(TestSpec.scala:10)
      at test.MultiExpectSpec.test(TestSpec.scala:10)
      at test.MultiExpectSpec$$anonfun$is$1.apply(TestSpec.scala:7)
      at test.MultiExpectSpec$$anonfun$is$1.apply(TestSpec.scala:7)

it also doesn't matter if is only a single failure, it reports multiple times anyway.

**Comment by etorreborre** [comment]
What's not to like about side-effects? I had a look at that and I don't find any obvious solution for now. I'll try to fix when I come back from holidays.

**Comment by etorreborre** [comment]
This is published as 2.4.16-SNAPSHOT.
