### ISSUE TITLE
NullPointerException in printFailure

### ISSUE THREAD

**Issue by sellout** [etorreborre/specs2#330]
Running our tests in SBT with the specs2 2.4.15.

Unfortunately, this happens after I changed some code, but without changing any tests, so I’m not sure which test might be causing this. I’ll try to narrow it down a bit more, but I’m hoping the culprit is more obvious to you than me.

```
[debug] Running TaskDef(slamdata.engine.RegressionSpec, specs2 Specification fingerprint, false, [SuiteSelector])
java.lang.NullPointerException
	at org.specs2.reporter.TextPrinter$PrintResult.printFailure(TextPrinter.scala:157)
	at org.specs2.reporter.TextPrinter$PrintResult.print$2(TextPrinter.scala:122)
	at org.specs2.reporter.TextPrinter$PrintResult.printResult(TextPrinter.scala:149)
	at org.specs2.reporter.TextPrinter$PrintResult$$anonfun$print$1.apply(TextPrinter.scala:113)
	at org.specs2.reporter.TextPrinter$PrintResult$$anonfun$print$1.apply(TextPrinter.scala:113)
	at scala.Option.map(Option.scala:145)
	at org.specs2.reporter.TextPrinter$PrintResult.print(TextPrinter.scala:113)
	at org.specs2.reporter.TextPrinter$PrintLine.print(TextPrinter.scala:62)
	at org.specs2.reporter.TextPrinter$$anonfun$printIO$1.apply(TextPrinter.scala:56)
	at org.specs2.reporter.TextPrinter$$anonfun$printIO$1.apply(TextPrinter.scala:54)
	at org.specs2.data.Reducerx$ExtendedReducer$$anonfun$$greater$greater$greater$3$$anonfun$apply$2.apply(Reducerx.scala:19)
	at scalaz.ReducerFunctions$$anon$5.snoc(Reducer.scala:160)
	at org.specs2.collection.Seqx$ExtendedSeq$$anonfun$reduceWith$1.apply(Seqx.scala:30)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1195)
	at org.specs2.collection.Seqx$ExtendedSeq.reduceWith(Seqx.scala:30)
	at org.specs2.reporter.TextPrinter$class.print(TextPrinter.scala:42)
	at org.specs2.reporter.SbtExporter.print(SbtReporter.scala:43)
	at org.specs2.reporter.TextExporting$$anonfun$export$1$$anonfun$apply$1.apply(TextExporting.scala:14)
	at org.specs2.reporter.TextExporting$$anonfun$export$1$$anonfun$apply$1.apply(TextExporting.scala:14)
	at org.specs2.specification.ExecutingSpecification.foreach(ExecutingSpecification.scala:24)
	at org.specs2.reporter.TextExporting$$anonfun$export$1.apply(TextExporting.scala:14)
	at org.specs2.reporter.TextExporting$$anonfun$export$1.apply(TextExporting.scala:13)
	at org.specs2.reporter.SbtExporter$$anonfun$export$2.apply(SbtReporter.scala:48)
	at org.specs2.reporter.SbtExporter$$anonfun$export$2.apply(SbtReporter.scala:47)
	at org.specs2.reporter.AllExporting$$anonfun$export$1$$anonfun$2$$anonfun$apply$1.apply(AllExporting.scala:32)
	at org.specs2.reporter.AllExporting$$anonfun$export$1$$anonfun$2$$anonfun$apply$1.apply(AllExporting.scala:32)
	at scala.collection.parallel.AugmentedIterableIterator$class.map2combiner(RemainsIterator.scala:115)
	at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1053)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1050)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by sellout** [comment]
Ok, quick guess – we have a toString definition that could NPE – so something trying to display that object needs to be careful.

**Comment by etorreborre** [comment]
That would be nice if you could narrow it down to the precise expectation that created this. There are some checks here and there against null values. I have an idea of a place which I could protect against null values but I would like to validate that and not shoot in the dark. Thanks.

**Comment by etorreborre** [comment]
I just published a SNAPSHOT version 2.4.17-SNAPSHOT containing a fix that might help with this issue. But I can't tell for sure until I can reproduce your case. Thanks for confirming if that helps.

**Comment by etorreborre** [comment]
Any news on that front?

**Comment by sellout** [comment]
Sorry, this will probably have to wait until I’m back at the office on Tuesday.

**Comment by etorreborre** [comment]
Hi again, did you have time to look at this issue?

**Comment by sellout** [comment]
Argh, I’m sorry – I just went to look at this, and the branch that ran into this issue is gone and things are different enough that it would be a significant amount of work to try to reproduce. Sorry I dropped the ball on this 😕

**Comment by etorreborre** [comment]
That's ok, as long as you're good, I'm good :-).
