### ISSUE TITLE
error when adding value to tuple

### ISSUE THREAD

**Issue by ghosthugger** [etorreborre/specs2#382]
i am using specs2 together with apache scalding

My tests works fine as long as i output the following:
    .write(TypedTsv[(String, Int, Float, Float, Float)](args("output")))

but when i add an extra Int to the tuple:
    .write(TypedTsv[(String, Int, Float, Float, Float, Int)](args("output")))

i get the callstack below.
The file is missing on my filesystem
(spotify)Gostas-MacBook-Pro:scalding gof$ cd /tmp/scalding/1e82f8dc-5667-4131-b60c-0acf1ffdb44e
(spotify)Gostas-MacBook-Pro:1e82f8dc-5667-4131-b60c-0acf1ffdb44e gof$ ls
com.twitter.scalding.FixedPathTypedDelimited261488024

are you truncating / wrapping the id generation somehow ?

org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/tmp/scalding/1e82f8dc-5667-4131-b60c-0acf1ffdb44e/com.twitter.scalding.FixedPathTypedDelimited576140677
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:197)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:208)
	at cascading.tap.hadoop.io.MultiRecordReaderIterator.initialize(MultiRecordReaderIterator.java:102)
	at cascading.tap.hadoop.io.MultiRecordReaderIterator.<init>(MultiRecordReaderIterator.java:80)
	at cascading.tap.hadoop.io.HadoopTupleEntrySchemeIterator.makeIterator(HadoopTupleEntrySchemeIterator.java:57)
	at cascading.tap.hadoop.io.HadoopTupleEntrySchemeIterator.<init>(HadoopTupleEntrySchemeIterator.java:44)
	at cascading.tap.hadoop.Hfs.openForRead(Hfs.java:518)
	at cascading.tap.hadoop.Hfs.openForRead(Hfs.java:109)
	at cascading.tap.Tap.openForRead(Tap.java:275)
	at com.twitter.scalding.HadoopMode$class.openForRead(Mode.scala:133)
	at com.twitter.scalding.HadoopTest.openForRead(Mode.scala:165)
	at com.twitter.scalding.HadoopTest.finalize(Mode.scala:203)
	at com.twitter.scalding.JobTest$$anonfun$runJob$2.apply(JobTest.scala:212)
	at com.twitter.scalding.JobTest$$anonfun$runJob$2.apply(JobTest.scala:212)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at com.twitter.scalding.JobTest.runJob(JobTest.scala:212)
	at com.twitter.scalding.JobTest.runHadoop(JobTest.scala:155)
	at com.spotify.keanu.TrigramFeaturesTest$$anonfun$1.apply$mcV$sp(TrigramFeaturesTest.scala:85)
	at com.spotify.keanu.TrigramFeaturesTest$$anonfun$1.apply(TrigramFeaturesTest.scala:85)
	at com.spotify.keanu.TrigramFeaturesTest$$anonfun$1.apply(TrigramFeaturesTest.scala:85)
	at org.specs2.mutable.SideEffectingCreationPaths$$anonfun$executeBlock$1.apply$mcV$sp(FragmentsBuilder.scala:282)
	at org.specs2.mutable.SideEffectingCreationPaths$class.replay(FragmentsBuilder.scala:254)
	at org.specs2.mutable.Specification.replay(Specification.scala:12)
	at org.specs2.mutable.FragmentsBuilder$class.fragments(FragmentsBuilder.scala:22)
	at org.specs2.mutable.Specification.fragments(Specification.scala:12)
	at org.specs2.mutable.SpecificationLike$class.is(Specification.scala:14)
	at org.specs2.mutable.Specification.is(Specification.scala:12)
	at org.specs2.specification.SpecificationStructure$$anonfun$content$1.apply(BaseSpecification.scala:55)
	at org.specs2.specification.SpecificationStructure$$anonfun$content$1.apply(BaseSpecification.scala:55)
	at org.specs2.specification.SpecificationStructure$class.map(BaseSpecification.scala:43)
	at org.specs2.mutable.Specification.map(Specification.scala:12)
	at org.specs2.specification.SpecificationStructure$class.content(BaseSpecification.scala:55)
	at org.specs2.mutable.Specification.content$lzycompute(Specification.scala:12)
	at org.specs2.mutable.Specification.content(Specification.scala:12)
	at org.specs2.runner.ClassRunner$$anonfun$apply$1$$anonfun$apply$2.apply(ClassRunner.scala:58)
	at org.specs2.runner.ClassRunner$$anonfun$apply$1$$anonfun$apply$2.apply(ClassRunner.scala:58)
	at org.specs2.control.Exceptions$class.tryo(Exceptions.scala:32)
	at org.specs2.control.Exceptions$.tryo(Exceptions.scala:109)
	at org.specs2.runner.ClassRunner$$anonfun$apply$1.apply(ClassRunner.scala:58)
	at org.specs2.runner.ClassRunner$$anonfun$apply$1.apply(ClassRunner.scala:57)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at org.specs2.runner.ClassRunner.apply(ClassRunner.scala:57)
	at org.specs2.runner.ClassRunner.start(ClassRunner.scala:35)
	at org.specs2.runner.NotifierRunner.start(NotifierRunner.scala:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jetbrains.plugins.scala.testingSupport.specs2.JavaSpecs2Runner.runSpecs2_old(JavaSpecs2Runner.java:132)
	at org.jetbrains.plugins.scala.testingSupport.specs2.JavaSpecs2Runner.runSingleTest(JavaSpecs2Runner.java:203)
	at org.jetbrains.plugins.scala.testingSupport.specs2.JavaSpecs2Runner.main(JavaSpecs2Runner.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by etorreborre** [comment]
So I assume that you found a solution to your issue. It wasn't related to specs2?
