### ISSUE TITLE
JUnitRunner does not tolerate companion objects

### ISSUE THREAD

**Issue by scottcarey** [etorreborre/specs2#477]
I believe that the error I see when a specification class has a companion object can be easily demonstrated in the specs2 test suite.  I get a failure in `junit\test` in sbt in specs with this change:

````diff
diff --git a/junit/src/test/scala/org/specs2/runner/JUnitRunnerSpec.scala b/junit/src/test/scala/org/specs2/runner/JUnitRunnerSpec.scala
index 1447c48..a2924da 100644
--- a/junit/src/test/scala/org/specs2/runner/JUnitRunnerSpec.scala
+++ b/junit/src/test/scala/org/specs2/runner/JUnitRunnerSpec.scala
@@ -51,6 +51,8 @@ class MainJUnitSpecification extends Specification { def is = s2"""
 """
 }
 
+object MainJUnitSpecification 
+
 @RunWith(classOf[JUnitRunner])
 object LinkedJUnitSpec extends mutable.Specification {
````

However, it may differ slightly from what I am seeing.  

The error I get in a hybrid java/scala maven project with a specification using surefire + JUnitRunner is below.  This did not happen on the prior version of specs2 (3.6.1) but does happen on 3.7.3

````
[ERROR] java.lang.ClassCastException: com.rr.mesos.util.JobUtilsTest$ cannot be cast to org.specs2.specification.core.SpecificationStructure
[ERROR] at org.specs2.runner.JUnitRunner$$anonfun$specification$2.apply(JUnitRunner.scala:25)
[ERROR] at scalaz.$bslash$div.fold(Either.scala:58)
[ERROR] at org.specs2.runner.JUnitRunner.specification$lzycompute(JUnitRunner.scala:23)
[ERROR] at org.specs2.runner.JUnitRunner.specification(JUnitRunner.scala:22)
[ERROR] at org.specs2.runner.JUnitRunner.specStructure$lzycompute(JUnitRunner.scala:37)
[ERROR] at org.specs2.runner.JUnitRunner.specStructure(JUnitRunner.scala:37)
[ERROR] at org.specs2.runner.JUnitRunner.getDescription$lzycompute(JUnitRunner.scala:34)
[ERROR] at org.specs2.runner.JUnitRunner.getDescription(JUnitRunner.scala:34)
[ERROR] at org.junit.runners.Suite.describeChild(Suite.java:123)
[ERROR] at org.junit.runners.Suite.describeChild(Suite.java:27)
[ERROR] at org.junit.runners.ParentRunner.shouldRun(ParentRunner.java:434)
[ERROR] at org.junit.runners.ParentRunner.filter(ParentRunner.java:382)
[ERROR] at org.junit.runner.manipulation.Filter.apply(Filter.java:97)
````

**Comment by etorreborre** [comment]
This is indeed a regression. Please try [`3.7.3-20160425190521-95ed957`](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.7.3-20160425190521-95ed957/).

**Comment by scottcarey** [comment]
version 3.7.3-20160425190521-95ed957 fixes it.

**Comment by etorreborre** [comment]
Yay!

**Comment by scottcarey** [comment]
Is the version above permanent?  or only a snapshot that will go away eventually?

Will there be a 3.7.4 to contain this?

I keep running into this when upgrading projects to 3.7.3.

**Comment by etorreborre** [comment]
This is not a snapshot so you can depend on it. I regularly do more "official" versions when I have accumulated enough features/fixes.
