### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by mslinn** [etorreborre/specs2#520]
This runs fine with `sbt test` under Scala 2.11 but fails under Scala-IDE 4.4.1 with: 
```
java.lang.NoSuchMethodError: org.specs2.specification.core.SpecificationStructure$.create(Ljava/lang/String;Ljava/lang/ClassLoader;Lscala/Option;)Lorg/specs2/control/ActionT;
	at org.specs2.runner.JUnitRunner.specification$lzycompute(JUnitRunner.scala:18)
	at org.specs2.runner.JUnitRunner.specification(JUnitRunner.scala:17)
	at org.specs2.runner.JUnitRunner.specStructure$lzycompute(JUnitRunner.scala:28)
	at org.specs2.runner.JUnitRunner.specStructure(JUnitRunner.scala:28)
	at org.specs2.runner.JUnitRunner.getDescription$lzycompute(JUnitRunner.scala:34)
	at org.specs2.runner.JUnitRunner.getDescription(JUnitRunner.scala:34)
	at org.junit.runner.Runner.testCount(Runner.java:41)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.countTestCases(JUnit4TestClassReference.java:30)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.countTests(RemoteTestRunner.java:479)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:447)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

`build.sbt`:
```
libraryDependencies ++= Seq(
  "org.specs2"    %% "specs2-core"  % "3.8.6" % "test" withSources(),
  "org.specs2"    %% "specs2-junit" % "3.6.6" % "test" withSources(),
  "org.scalatest" %% "scalatest"    % "3.0.0" % "test" withSources()
)
scalacOptions in Test ++= Seq("-Yrangepos") // Is this helpful?
```

`src/test/scala/TestSpecs2Demo.scala`:
```
import org.specs2.mutable._
import org.specs2.runner.JUnitRunner
import org.junit.runner.RunWith

@RunWith(classOf[JUnitRunner])
class TestSpecs2Demo extends Specification {
  "The 'Hello world' string" should {
    "contain 11 characters" in {
      "Hello world" must have size 11
    }
  }
}
```
What am I missing?

**Comment by etorreborre** [comment]
You have a dependency on `3.6.6` in your dependencies instead of `3.8.6`:
```
"org.specs2"    %% "specs2-junit" % "3.6.6" % "test" withSources()
```

**Comment by mslinn** [comment]
I feel stupid but grateful :)

**Comment by etorreborre** [comment]
No worries, it's not always obvious to see such typos :-).
