### ISSUE TITLE
Class / object detection suppresses initialization errors

### ISSUE THREAD

**Issue by stephenh** [etorreborre/specs2#535]
If I have a spec like:

```
class FooSpec extends Specification {
  val a = ???
}
```

When I execute this, I get a `ClassNotFoundException: FooSpec$`:

```
java.lang.ClassNotFoundException: FooSpec$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.specs2.reflect.Classes$$anonfun$loadClassEither$1.apply(Classes.scala:140)
	at org.specs2.reflect.Classes$$anonfun$loadClassEither$1.apply(Classes.scala:140)
	at org.specs2.control.ActionT$$anonfun$safe$1.apply(ActionT.scala:89)
	at org.specs2.control.ActionT$$anonfun$reader$1$$anonfun$apply$6.apply(ActionT.scala:80)
	at org.specs2.control.Status$.safe(Status.scala:100)
	at org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
	at org.specs2.control.StatusT$$anonfun$safe$1.apply(StatusT.scala:62)
	at scalaz.syntax.ToApplicativeOps$$anon$1.self$lzycompute(ApplicativeSyntax.scala:29)
	at scalaz.syntax.ToApplicativeOps$$anon$1.self(ApplicativeSyntax.scala:29)
	at scalaz.syntax.ToApplicativeOps$ApplicativeIdV$$anonfun$point$1.apply(ApplicativeSyntax.scala:33)
	at scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:268)
	at scalaz.WriterTApplicative$$anonfun$point$1.apply(WriterT.scala:268)
	at scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
	at scalaz.effect.IO$$anonfun$apply$19$$anonfun$apply$20.apply(IO.scala:136)
	at scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
	at scalaz.FreeFunctions$$anonfun$return_$1.apply(Free.scala:326)
	at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:172)
	at scalaz.Free.go2$1(Free.scala:119)
	at scalaz.Free.go(Free.scala:122)
	at scalaz.Free.run(Free.scala:172)
	at scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
	at scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
	at org.specs2.runner.JUnitRunner.specification$lzycompute(JUnitRunner.scala:19)
	at org.specs2.runner.JUnitRunner.specification(JUnitRunner.scala:18)
	at org.specs2.runner.JUnitRunner.specStructure$lzycompute(JUnitRunner.scala:29)
	at org.specs2.runner.JUnitRunner.specStructure(JUnitRunner.scala:29)
	at org.specs2.runner.JUnitRunner.getDescription$lzycompute(JUnitRunner.scala:35)
	at org.specs2.runner.JUnitRunner.getDescription(JUnitRunner.scala:35)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:85)
```

The reason AFAICT is that the "detect FooSpec or FooSpec$" logic treats any initialization failure for `FooSpec` as "well, guess I should try `FooSpec$`", which also fails, but in the process ends up completely suppressing the real failure.

(Disclaimer, I'm using specs 3.6 and haven't technically tried the above reproduction in a clean/minimal project, but it matches what I've seen in my codebase.)

**Comment by etorreborre** [comment]
Can you please try a more recent version of specs2, like `3.8.7`. Here is the corresponding failure:
```scala
[error]
[error] cannot create an instance for class user.FooSpec
[error]   caused by scala.NotImplementedError: an implementation is missing
[error]
[error] STACKTRACE
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[error]   org.specs2.reflect.Classes.$anonfun$createInstanceForConstructor$1(Classes.scala:61)
[error]   org.specs2.reflect.Classes.newInstance(Classes.scala:83)
[error]   org.specs2.reflect.Classes.createInstanceForConstructor(Classes.scala:61)
[error]   org.specs2.reflect.Classes.findInstance(Classes.scala:47)
[error]   org.specs2.reflect.Classes.createInstanceFromClass(Classes.scala:29)
[error]   org.specs2.reflect.Classes.createInstanceFromClass$(Classes.scala:28)
[error]   org.specs2.reflect.Classes$.createInstanceFromClass(Classes.scala:109)
[error]   org.specs2.reflect.Classes.$anonfun$createInstance$1(Classes.scala:25)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:379)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.IntoPolyLower2$$anon$3.$anonfun$apply$8(IntoPoly.scala:60)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:376)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.Interpret.$anonfun$interpretLoop$11(Interpret.scala:197)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:376)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.CollectedUnions.$anonfun$othersEff$1(Unions.scala:97)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:379)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:341)
[error]   org.specs2.control.eff.CollectedUnions.$anonfun$continuation$1(Unions.scala:84)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:376)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.Interpret$$anon$1.$anonfun$onEffect$1(Interpret.scala:52)
[error]   scalaz.std.EitherInstances$$anon$13.bimap(Either.scala:54)
[error]   scalaz.std.EitherInstances$$anon$13.bimap(Either.scala:51)
[error]   scalaz.syntax.BifunctorOps.bimap(BifunctorSyntax.scala:9)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:52)
[error]   org.specs2.control.eff.Interpret$$anon$1.onApplicativeEffect(Interpret.scala:60)
[error]   org.specs2.control.eff.Interpret$$anon$1.onApplicativeEffect(Interpret.scala:44)
[error]   org.specs2.control.eff.Interpret.go$1(Interpret.scala:199)
[error]   org.specs2.control.eff.Interpret.interpretLoop(Interpret.scala:206)
[error]   org.specs2.control.eff.Interpret.interpretLoop$(Interpret.scala:141)
[error]   org.specs2.control.eff.Interpret$.interpretLoop(Interpret.scala:586)
[error]   org.specs2.control.eff.Interpret.interpret(Interpret.scala:70)
[error]   org.specs2.control.eff.Interpret.interpret$(Interpret.scala:43)
[error]   org.specs2.control.eff.Interpret$.interpret(Interpret.scala:586)
[error]   org.specs2.control.eff.Interpret.interpret1(Interpret.scala:77)
[error]   org.specs2.control.eff.Interpret.interpret1$(Interpret.scala:76)
[error]   org.specs2.control.eff.Interpret$.interpret1(Interpret.scala:586)
[error]   org.specs2.control.eff.ErrorInterpretation.runError(ErrorEffect.scala:86)
[error]   org.specs2.control.eff.ErrorInterpretation.runError$(ErrorEffect.scala:67)
[error]   org.specs2.control.eff.ErrorEffect$.runError(ErrorEffect.scala:201)
[error]   org.specs2.control.eff.syntax.error$ErrorEffectOps.runError(error.scala:15)
[error]   org.specs2.control.package$.executeAction(package.scala:66)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure$lzycompute(SbtRunner.scala:42)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure(SbtRunner.scala:39)
[error]   org.specs2.runner.SbtRunner$$anon$4.execute(SbtRunner.scala:53)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:296)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:286)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error]
[error]   CAUSED BY scala.NotImplementedError: an implementation is missing
[error]   scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
[error]   user.FooSpec.<init>(TestSpec.scala:22)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[error]   org.specs2.reflect.Classes.$anonfun$createInstanceForConstructor$1(Classes.scala:61)
[error]   org.specs2.reflect.Classes.newInstance(Classes.scala:83)
[error]   org.specs2.reflect.Classes.createInstanceForConstructor(Classes.scala:61)
[error]   org.specs2.reflect.Classes.findInstance(Classes.scala:47)
[error]   org.specs2.reflect.Classes.createInstanceFromClass(Classes.scala:29)
[error]   org.specs2.reflect.Classes.createInstanceFromClass$(Classes.scala:28)
[error]   org.specs2.reflect.Classes$.createInstanceFromClass(Classes.scala:109)
[error]   org.specs2.reflect.Classes.$anonfun$createInstance$1(Classes.scala:25)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:379)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.IntoPolyLower2$$anon$3.$anonfun$apply$8(IntoPoly.scala:60)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:376)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.Interpret.$anonfun$interpretLoop$11(Interpret.scala:197)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:376)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.CollectedUnions.$anonfun$othersEff$1(Unions.scala:97)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:379)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:341)
[error]   org.specs2.control.eff.CollectedUnions.$anonfun$continuation$1(Unions.scala:84)
[error]   org.specs2.control.eff.Arrs.go$1(Eff.scala:376)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:392)
[error]   org.specs2.control.eff.Interpret$$anon$1.$anonfun$onEffect$1(Interpret.scala:52)
[error]   scalaz.std.EitherInstances$$anon$13.bimap(Either.scala:54)
[error]   scalaz.std.EitherInstances$$anon$13.bimap(Either.scala:51)
[error]   scalaz.syntax.BifunctorOps.bimap(BifunctorSyntax.scala:9)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:52)
[error]   org.specs2.control.eff.Interpret$$anon$1.onApplicativeEffect(Interpret.scala:60)
[error]   org.specs2.control.eff.Interpret$$anon$1.onApplicativeEffect(Interpret.scala:44)
[error]   org.specs2.control.eff.Interpret.go$1(Interpret.scala:199)
[error]   org.specs2.control.eff.Interpret.interpretLoop(Interpret.scala:206)
[error]   org.specs2.control.eff.Interpret.interpretLoop$(Interpret.scala:141)
[error]   org.specs2.control.eff.Interpret$.interpretLoop(Interpret.scala:586)
[error]   org.specs2.control.eff.Interpret.interpret(Interpret.scala:70)
[error]   org.specs2.control.eff.Interpret.interpret$(Interpret.scala:43)
[error]   org.specs2.control.eff.Interpret$.interpret(Interpret.scala:586)
[error]   org.specs2.control.eff.Interpret.interpret1(Interpret.scala:77)
[error]   org.specs2.control.eff.Interpret.interpret1$(Interpret.scala:76)
[error]   org.specs2.control.eff.Interpret$.interpret1(Interpret.scala:586)
[error]   org.specs2.control.eff.ErrorInterpretation.runError(ErrorEffect.scala:86)
[error]   org.specs2.control.eff.ErrorInterpretation.runError$(ErrorEffect.scala:67)
[error]   org.specs2.control.eff.ErrorEffect$.runError(ErrorEffect.scala:201)
[error]   org.specs2.control.eff.syntax.error$ErrorEffectOps.runError(error.scala:15)
[error]   org.specs2.control.package$.executeAction(package.scala:66)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure$lzycompute(SbtRunner.scala:42)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure(SbtRunner.scala:39)
[error]   org.specs2.runner.SbtRunner$$anon$4.execute(SbtRunner.scala:53)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:296)
[error]   sbt.ForkMain$Run$2.call(ForkMain.java:286)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error]
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	user.FooSpec
[error] (tests/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
```
