### ISSUE TITLE
Test output broken in IntelliJ (Specs2 3.9.x)

### ISSUE THREAD

**Issue by mttkay** [etorreborre/specs2#597]
I just upgraded to Specs2 3.9.5, and while running tests via sbt works fine, running tests in IntelliJ (2017.2.3) only works when they pass; if there is a failure, Specs2 produces output the IDE seemingly doesn't understand:

(console output:)
```
##teamcity[testFailed name='truncates response to three elements without a sub' message='|nTopItem(None,7,None)|nTopItem(None,8,None)|nTopItem(None,9,None)|n- TopItem(None,10,None)|n' details='java.lang.Exception: |nTopItem(None,7,None)|nTopItem(None,8,None)|nTopItem(None,9,None)|n- TopItem(None,10,None)|n|n	at org.specs2.matcher.MatchResultStackTrace.setStacktrace(Expectations.scala:57)|n	at org.specs2.matcher.MatchResultStackTrace.setStacktrace$(Expectations.scala:55)|n	at org.specs2.mutable.Specification.setStacktrace(Specification.scala:15)|n	at org.specs2.matcher.ExpectationsCreation.checkFailure(Expectations.scala:37)|n	at org.specs2.matcher.ExpectationsCreation.checkFailure$(Expectations.scala:36)|n	at org.specs2.mutable.Specification.checkFailure(Specification.scala:15)|n	at org.specs2.matcher.ThrownExpectables$$anon$1.check(ThrownExpectations.scala:40)|n	at org.specs2.matcher.Expectable.applyMatcher(Expectable.scala:50)|n	at org.specs2.matcher.ThrownExpectables$$anon$1.applyMatcher(ThrownExpectations.scala:39)|n	at org.specs2.matcher.TypedEqual$TypedEqualExpectation.$eq$eq$eq$eq(TypedEqual.scala:24)|n	at com.soundcloud.creatorstats.topk.TopkServiceSpec$$anon$12.<init>(TopkServiceSpec.scala:286)|n	at com.soundcloud.creatorstats.topk.TopkServiceSpec.$anonfun$new$83(TopkServiceSpec.scala:283)|n	at org.specs2.matcher.Scope$$anon$3.$anonfun$asResult$1(ThrownExpectations.scala:152)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.Result$$anon$10.asResult(Result.scala:229)|n	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)|n	at org.specs2.matcher.Scope$$anon$3.asResult(ThrownExpectations.scala:152)|n	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)|n	at org.specs2.specification.core.AsExecution$$anon$1.$anonfun$execute$1(AsExecution.scala:15)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.Result$$anon$10.asResult(Result.scala:229)|n	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)|n	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:33)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.AsResult$.safely(AsResult.scala:33)|n	at org.specs2.specification.core.Execution$.$anonfun$result$2(Execution.scala:193)|n	at org.specs2.specification.core.Execution$.$anonfun$withEnv$3(Execution.scala:196)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.Result$$anon$10.asResult(Result.scala:229)|n	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)|n	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:33)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.AsResult$.safely(AsResult.scala:33)|n	at org.specs2.specification.core.Execution$.$anonfun$withEnv$2(Execution.scala:196)|n	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)|n	at scala.util.Success.$anonfun$map$1(Try.scala:251)|n	at scala.util.Success.map(Try.scala:209)|n	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)|n	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)|n	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)|n	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)|n	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)|n	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)|n	at java.lang.Thread.run(Thread.java:745)|n' timestamp='2017-09-01T16:11:19.812' nodeId='79']

Process finished with exit code 0
```
The UI meanwhile keeps spinning its wheels because it doesn't seem to understand that the test has finished with a failure.

I added the following dependencies to the projects:

```
  "org.specs2" %% "specs2-core" % specs2Version % "it,test",
  "org.specs2" %% "specs2-junit" % specs2Version % "it,test",
  "org.specs2" %% "specs2-mock" % specs2Version % "it,test"
```

I'm not sure I understand how the IDE and Specs2 negotiate the test output (`Printer`) being used, so this could just as well be an IJ issue. 

Any thoughts/ideas?

**Comment by etorreborre** [comment]
I'm going to need a reproducible test case because it works ok for me.

If you want to investigate what's going on, maybe simply using the debugger, you can have a look at the [JavaSpecs2Notifier](https://github.com/JetBrains/intellij-scala/blob/26f8c5b659c906ac645463d67602dcb13f83a4a0/Runners/src/org/jetbrains/plugins/scala/testingSupport/specs2/JavaSpecs2Notifier.java)

**Comment by mttkay** [comment]
Thanks @etorreborre -- we think we distilled it down to being a problem with matching sequences. Below is what we think is an "mcve". It appears that only tests are affected that contain `Seq`s or `List`s and only when using the equals matcher and the objects do not equal:

```scala
import org.specs2.mutable.Specification

class Spec extends Specification {

  "fails with normal output" in {
    Seq(1) !=== Seq(1)
  }

  "fails with broken output" in {
    Seq(1) ==== Seq(2)
  }

}
```
Here, the first test fails normally with the expected output:

```
List(1) == 'List(1)'
java.lang.Exception: List(1) == 'List(1)'
```

whereas the second test, which should produce the same output, fails with

```
##teamcity[testFailed name='fails with broken output' message='|n- 1|n+ 2|n' details='java.lang.Exception: |n- 1|n+ 2|n|n	at org.specs2.matcher.MatchResultStackTrace.setStacktrace(Expectations.scala:57)|n	at org.specs2.matcher.MatchResultStackTrace.setStacktrace$(Expectations.scala:55)|n	at org.specs2.mutable.Specification.setStacktrace(Specification.scala:15)|n	at org.specs2.matcher.ExpectationsCreation.checkFailure(Expectations.scala:37)|n	at org.specs2.matcher.ExpectationsCreation.checkFailure$(Expectations.scala:36)|n	at org.specs2.mutable.Specification.checkFailure(Specification.scala:15)|n	at org.specs2.matcher.ThrownExpectables$$anon$1.check(ThrownExpectations.scala:40)|n	at org.specs2.matcher.Expectable.applyMatcher(Expectable.scala:50)|n	at org.specs2.matcher.ThrownExpectables$$anon$1.applyMatcher(ThrownExpectations.scala:39)|n	at org.specs2.matcher.TypedEqual$TypedEqualExpectation.$eq$eq$eq$eq(TypedEqual.scala:24)|n	at Spec.$anonfun$new$4(Spec.scala:10)|n	at org.specs2.matcher.MatchResult$$anon$12.$anonfun$asResult$1(MatchResult.scala:343)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.Result$$anon$10.asResult(Result.scala:229)|n	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)|n	at org.specs2.matcher.MatchResult$$anon$12.asResult(MatchResult.scala:343)|n	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)|n	at org.specs2.specification.core.AsExecution$$anon$1.$anonfun$execute$1(AsExecution.scala:15)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.Result$$anon$10.asResult(Result.scala:229)|n	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)|n	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:33)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.AsResult$.safely(AsResult.scala:33)|n	at org.specs2.specification.core.Execution$.$anonfun$result$2(Execution.scala:193)|n	at org.specs2.specification.core.Execution$.$anonfun$withEnv$3(Execution.scala:196)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.Result$$anon$10.asResult(Result.scala:229)|n	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)|n	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:33)|n	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)|n	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)|n	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)|n	at org.specs2.execute.AsResult$.safely(AsResult.scala:33)|n	at org.specs2.specification.core.Execution$.$anonfun$withEnv$2(Execution.scala:196)|n	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)|n	at scala.util.Success.$anonfun$map$1(Try.scala:251)|n	at scala.util.Success.map(Try.scala:209)|n	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)|n	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)|n	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)|n	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)|n	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)|n	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)|n	at java.lang.Thread.run(Thread.java:745)|n' timestamp='2017-09-04T11:37:07.783' nodeId='3']
```

Can't make heads or tails of this, although we admittedly didn't end up debugging Specs2. Might look into that later today. Definitely bizarre. Any ideas so far?

**Comment by etorreborre** [comment]
Unfortunately I still can't reproduce the issue. Can you please create an issue on the Intellij tracker?

**Comment by mttkay** [comment]
Filed as https://youtrack.jetbrains.com/issue/SCL-12533

@etorreborre Just to double check; does the following test output (as produced by sbt--no IJ involved here) look expected to you?

```
[info] Spec
[info]
[error] x fails with normal output
[error]  List(1) == 'List(1)' (Spec.scala:6)
[info]
[error] x fails with broken output
[error]  List(1) != List(2) (Spec.scala:10)
[info]
[error] Added (1)
[error] 1
[info]
[error] Missing (1)
[error] 2
[info]
[info]
[info]
[info]
[info] Total for specification Spec
[info] Finished in 269 ms
[info] 2 examples, 2 failures, 0 error
[info]
[error] Failed: Total 2, Failed 2, Errors 0, Passed 0
[error] Failed tests:
[error] 	Spec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 8 s, completed Sep 5, 2017 4:23:42 PM
```
I just want to make sure the problem is really specific to IntelliJ.

Feel free to close this out here if there's nothing to be done on the Specs2 end.

**Comment by etorreborre** [comment]
Yes that's the expected output. The first test uses `==` to check for equality, the second one relies on the `Diffable` typeclass for this and can "drill-in" the values to display differences.
