### ISSUE TITLE
playframework testing scala application returns error

### ISSUE THREAD

**Issue by holzfelix** [etorreborre/specs2#626]
I want to write Tests for my playframework scala application.

My test looks like this:
```scala
package controllers

import java.sql.Date
import java.util

import be.objectify.deadbolt.scala.DeadboltHandler
import models.ProcessInstancesModel
import play.api.Application
import play.api.inject.bind
import play.api.inject.guice.GuiceApplicationBuilder
import play.api.libs.json.Json
import play.api.mvc.{AnyContentAsJson, Result}
import play.api.test.{FakeHeaders, FakeRequest, PlaySpecification, WithApplication}
import play.api.test.Helpers._

import scala.concurrent.Future
import collection.mutable.Stack

class ProcessInstancesControllerSpec extends PlaySpecification {
  sequential

  "ProcessInstancesController" should {

    def ProcessInstancesController(implicit app: Application) = {
      val app2ProcessInstancesController = Application.instanceCache[controllers.ProcessInstancesController]
      app2ProcessInstancesController(app)
    }

    implicit val projectInstanceFormat = Json.format[ProcessInstancesModel]

    val validProcessInstanceJson = AnyContentAsJson(Json.parse(
      """{
        |   "processTemplateId":47,
        |   "startedAt":"2017-12-19 13:50:24",
        |   "updatedAt":"2017-12-19 13:50:24",
        |   "status":"started",
        |   "comment":"",
        |   "deleted":false,
        |   "clientId":35,
        |   "steps":[
        |      {
        |         "id":62,
        |         "title":"Scala Test",
        |         "createdat":"2017-12-12 11:09:56.0",
        |         "updatedat":"2017-12-12 11:09:56.0",
        |         "deadline":1512946800000,
        |         "stepType":1,
        |         "position":0,
        |         "deleted":false,
        |         "processTemplate_id":47,
        |         "derivedProcesses":[
        |
        |         ],
        |         "prerequisites":[
        |
        |         ],
        |         "stepPrerequisites":[
        |
        |         ],
        |         "stepPostconditions":[
        |
        |         ],
        |         "stepDerivedProcesses":[
        |
        |         ],
        |         "stepSubProcesses":[
        |
        |         ],
        |         "stepResponsible":[
        |
        |         ],
        |         "postconditions":[
        |
        |         ],
        |         "addProcessToProcessStepArray":[
        |
        |         ],
        |         "responsible":[
        |
        |         ]
        |      }
        |   ]
        |}""".stripMargin))


//    val app = GuiceApplicationBuilder().overrides(bind[DeadboltHandler].to[DeadboltHandlerMock])

    val application: Application = GuiceApplicationBuilder().build()

    "respond to the index Action" in new WithApplication(application) {
      val Some(result) = route(app, FakeRequest(GET, "/processInstanceAll/35"))
      status(result) must equalTo(OK)
      contentType(result) must beSome("text/html")
      charset(result) must beSome("utf-8")
      contentAsString(result)         must contain("[{\"data\":{\"id\":117")
      contentAsString(result)        must contain("processTemplateId")
      contentAsString(result)         must contain("clientId")
//      contentAsString(result) must contain("Hello Bob")
    }
```

When I try to run it I got this error Message: `InvocationTargetException for 'main' in org.specs2.NotifierRunner: null`

What could be the problem in this case?

thanks in advance.

**Comment by holzfelix** [comment]
When I do it this way:

` val app = new GuiceApplicationBuilder()

    println("TEST5", app)
    "list all process instances by client" in new WithApplication(app.build) {`

I got this error:

Fatal execution error, caused by play.api.libs.logback.LogbackLoggerConfigurator.configure

**Comment by holzfelix** [comment]
I found this example from playframework: 
https://github.com/playframework/playframework/blob/master/documentation/manual/working/scalaGuide/main/tests/code/specs2/ScalaFunctionalTestSpec.scala

When I run this I got the same error:  InvocationTargetException for 'main' in org.specs2.NotifierRunner: null

**Comment by etorreborre** [comment]
I don't know exactly what's wrong but I suspect that something is throwing an exception that's more or less swallowed. Can you use `sbt> testOnly *YourSpec* -- fullstacktrace` and post the stacktrace?

**Comment by etorreborre** [comment]
Even better would be to have a small Github project reproducing the issue :-)

**Comment by holzfelix** [comment]
Stacktrace Returns:

```
[error] Uncaught exception when running controllers.ProcessInstancesControllerSpec: java.lang.AbstractMethodError: play.api.libs.logback.LogbackLoggerConfigurator.configure(Lplay/api/Environment;Lplay/api/Configuration;Lscala/collection/immutable/Map;)V
sbt.ForkMain$ForkError: java.lang.AbstractMethodError: play.api.libs.logback.LogbackLoggerConfigurator.configure(Lplay/api/Environment;Lplay/api/Configuration;Lscala/collection/immutable/Map;)V
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$1.apply(GuiceApplicationBuilder.scala:122)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$1.apply(GuiceApplicationBuilder.scala:121)
        at scala.Option.map(Option.scala:146)
        at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:121)
        at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:100)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at controllers.ProcessInstancesControllerSpec$$anonfun$2.apply(ProcessInstancesControllerSpec.scala:86)
        at controllers.ProcessInstancesControllerSpec$$anonfun$2.apply(ProcessInstancesControllerSpec.scala:22)
        at org.specs2.specification.dsl.mutable.EffectBlocks$$anonfun$addBlock$1.apply$mcV$sp(EffectBlocks.scala:93)
        at org.specs2.specification.dsl.mutable.EffectBlocks.replay$lzycompute(EffectBlocks.scala:63)
        at org.specs2.specification.dsl.mutable.EffectBlocks.replay(EffectBlocks.scala:59)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder$class.org$specs2$specification$dsl$mutable$MutableFragmentBuilder$$replayFragments(MutableFragmentBuilder.scala:47)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder$$anonfun$specificationFragments$1.apply(MutableFragmentBuilder.scala:37)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder$$anonfun$specificationFragments$1.apply(MutableFragmentBuilder.scala:34)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder$$anonfun$specificationStructure$1$$anonfun$apply$1.apply(MutableFragmentBuilder.scala:43)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder$$anonfun$specificationStructure$1$$anonfun$apply$1.apply(MutableFragmentBuilder.scala:43)
        at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:25)
        at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:25)
        at org.specs2.specification.core.SpecStructure$$anonfun$1.apply(SpecStructure.scala:28)
        at org.specs2.specification.core.SpecStructure$$anonfun$1.apply(SpecStructure.scala:28)
        at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:25)
        at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:25)
        at org.specs2.specification.core.SpecStructure$$anonfun$2.apply(SpecStructure.scala:29)
        at org.specs2.specification.core.SpecStructure$$anonfun$2.apply(SpecStructure.scala:29)
        at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:25)
        at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:25)
        at org.specs2.specification.core.SpecStructure$$anonfun$3.apply(SpecStructure.scala:30)
        at org.specs2.specification.core.SpecStructure$$anonfun$3.apply(SpecStructure.scala:30)
        at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:25)
        at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:25)
        at org.specs2.specification.core.SpecStructure.contents(SpecStructure.scala:27)
        at org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:46)
        at org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:39)
        at org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:72)
        at org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:72)
        at org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:35)
        at org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:35)
        at org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:20)
        at org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:19)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:63)
        at scalaz.WriterT$$anonfun$flatMapF$1.apply(WriterT.scala:62)
        at scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:62)
        at scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:61)
        at scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
        at scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$1.apply(Free.scala:60)
        at scalaz.Free.resume(Free.scala:72)
        at scalaz.Free.go2$1(Free.scala:118)
        at scalaz.Free.go(Free.scala:122)
        at scalaz.Free.run(Free.scala:172)
        at scalaz.effect.IO$class.unsafePerformIO(IO.scala:22)
        at scalaz.effect.IOFunctions$$anon$6.unsafePerformIO(IO.scala:227)
        at org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:37)
        at sbt.ForkMain$Run$2.call(ForkMain.java:296)
        at sbt.ForkMain$Run$2.call(ForkMain.java:286)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Yes Sure I will Build a small Project **thanks**

**Comment by holzfelix** [comment]
https://github.com/holzfelix/processInstances

I've added the project to github

**Comment by etorreborre** [comment]
This stacktrace leads me to think that this is an issue with your dependencies. You should check the `LogbackLoggerConfigurator. configure` call in different versions of the library to check which one is supposed to be called.

**Comment by holzfelix** [comment]
where can I find which logger I need for play framework 2.5.14? never changed something on logger

**Comment by etorreborre** [comment]
Also I think the exception must be thrown from a place where we build the specification:
```
"this is a block of examples" >> {
   val myApp = // throws an exception here
   "this is an example" in {
      1 must_== 1
   }
}
```
In that case you will get some better reporting if you use a `lazy val`.

**Comment by etorreborre** [comment]
Unfortunately I am not a Play user so I can't really help you here.

**Comment by holzfelix** [comment]
Thanks I solved it. It was a dependency problem Thanks

**Comment by etorreborre** [comment]
Great, I'm closing then.

**Comment by davidilieberman** [comment]
holzfelix -- any chance you could describe the dependency injection problem and solution? I'm having the same issue. Thanks!

**Comment by luberg** [comment]
+1 @holzfelix

**Comment by konradwudkowski** [comment]
+1 @holzfelix
