### ISSUE TITLE
Specs2 throws java.lang.NoSuchMethodError with Mockito

### ISSUE THREAD

**Issue by eximius313** [etorreborre/specs2#630]
Here is the test case: [Specs2Mockito.zip](https://github.com/etorreborre/specs2/files/1649168/Spec2Mockito.zip).
run `sbt test` and it will fail with:
```
[error] Test controllers.HomeControllerTest.testMockito failed: java.lang.NoSuchMethodError: org.mockito.internal.invocation.ArgumentsProcessor.expandArgs(Lorg/mockito/internal/invocation/MockitoMethod;[Ljava/lang/Object;)[Ljava/lang/Object;, took 3.761 sec
[error]     at org.mockito.internal.creation.bytebuddy.InterceptedInvocation.<init>(InterceptedInvocation.java:46)
[error]     at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.createInvocation(MockMethodInterceptor.java:75)
[error]     at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:65)
[error]     at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:51)
[error]     at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:135)
[error]     at service.UserService$MockitoMock$2068255624.doSomething(Unknown Source)
[error]     at controllers.HomeController.index(HomeController.java:24)
[error]     at controllers.HomeControllerTest.testMockito(HomeControllerTest.java:28)
[error]     ...
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         controllers.HomeControllerTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 15 s, completed 2018-01-20 19:47:38
```

go to `build.sbt` , comment line `#13`, run `sbt test` -> everything works fine

**Comment by etorreborre** [comment]
I think that you can uncomment the dependency with mockito in your build file. This overrides the dependency which specs2 needs for version `3.8.9` and it is `mockito-core-1.9.5`.

**Comment by eximius313** [comment]
> I think that you can uncomment the dependency with mockito in your build file

umm... dependency with mockito is not commented in my build file, so I'm not sure what exactly do you mean

>  specs2 needs for version 3.8.9 and it is mockito-core-1.9.5

Do you mean that specs2 in version `3.8.9` depends on `mockito-core-1.9.5`? 
Could you possibly upgrade Specs2 to use Mockito 2?

**Comment by etorreborre** [comment]
The upgrade has been done in specs2 4.0.2 (the latest in the 4.x series).

**Comment by eximius313** [comment]
When I replace this line: `specs2 % Test`
with this line: `specs2 % "4.0.2" % Test`
I get:
```
[error] java.lang.IllegalArgumentException: requirement failed: Configurations already specified for module com.typesafe.play:play-specs2:2.6.11:4.0.2
[error]         at scala.Predef$.require(Predef.scala:277)
[error]         at sbt.librarymanagement.DependencyBuilders.moduleIDConfigurable(DependencyBuilders.scala:30)
[error]         at sbt.librarymanagement.DependencyBuilders.moduleIDConfigurable$(DependencyBuilders.scala:29)
[error]         at sbt.package$.moduleIDConfigurable(package.scala:6)
[error]         at $267463d4231a1ad0a7ac$.$anonfun$$sbtdef$1(/workspaces/Spec2Mockito/build.sbt:13)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:197)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] java.lang.IllegalArgumentException: requirement failed: Configurations already specified for module com.typesafe.play:play-specs2:2.6.11:4.0.2
```

**Comment by etorreborre** [comment]
I have never had this before, can you please try to ask on the sbt gitter channel?

**Comment by eximius313** [comment]
Here you have the test case: [Specs2Mockito.zip](https://github.com/etorreborre/specs2/files/1655576/Specs2Mockito.zip)
just run `sbt` please

**Comment by etorreborre** [comment]
I was just writing this because of the `sbt` stacktrace and the mention of `Configurations` which is a `sbt` thing. I unfortunately don't have the time now to investigate this issue more in depth, this is why I'm suggesting to ask the sbt people (or maybe the play people) who might spot the issue right away.
