### ISSUE TITLE
A seed could not be captured for a ScalaCheck property

### ISSUE THREAD

**Issue by buzden** [etorreborre/specs2#718]
Specs2-4.3.4 introduced (comparing to 4.3.3) a bug which leads to an exception with the following text

> A seed could not be captured for a ScalaCheck property and no seed was set on the prop or set on the command line.

It is done when an instance of `org.scalacheck.Properties` or result of `Discipline.checkAll` is used in `def is` in `Specification`. In my case, cats-laws was the source of `Properties` or `Laws#RulesSet` (but I doubt it matters).

Exception's stacktrace is
```
java.lang.Exception: A seed could not be captured for a ScalaCheck property and no seed was set on the prop or set on the command line. Please report this issue to http://github.com/etorreborre/specs2/issues
	at org.specs2.scalacheck.ScalaCheckPropertyCheck.$anonfun$check$2(ScalaCheckPropertyCheck.scala:32)
	at scala.Option.getOrElse(Option.scala:121)
	at org.specs2.scalacheck.ScalaCheckPropertyCheck.initialSeed$lzycompute$1(ScalaCheckPropertyCheck.scala:32)
	at org.specs2.scalacheck.ScalaCheckPropertyCheck.initialSeed$1(ScalaCheckPropertyCheck.scala:31)
	at org.specs2.scalacheck.ScalaCheckPropertyCheck.$anonfun$check$4(ScalaCheckPropertyCheck.scala:56)
	at org.specs2.scalacheck.ScalaCheckPropertyCheck.displaySeed$1(ScalaCheckPropertyCheck.scala:124)
	at org.specs2.scalacheck.ScalaCheckPropertyCheck.$anonfun$prettyResult$1(ScalaCheckPropertyCheck.scala:151)
	at org.scalacheck.util.Pretty$$anon$1.apply(Pretty.scala:35)
	at org.specs2.scalacheck.ScalaCheckPropertyCheck.check(ScalaCheckPropertyCheck.scala:56)
	at org.specs2.scalacheck.ScalaCheckPropertyCheck.check$(ScalaCheckPropertyCheck.scala:27)
	at <UsedTestClass>.check
	at org.typelevel.discipline.specs2.Discipline.$anonfun$checkAll$2(Discipline.scala:16)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:121)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:121)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$result$1(Execution.scala:305)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$3(Execution.scala:323)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:121)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:121)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$2(Execution.scala:323)
	at org.specs2.specification.core.Execution.$anonfun$startExecution$3(Execution.scala:135)
```

**Comment by buzden** [comment]
I don't know what to think but the problem seems to be more complicated.

While using specs2-4.3.3, I've updated [spire](https://github.com/non/spire)'s project dependency from 0.14.1 to 0.16.0 (or 0.15.0) and was given the same (seemingly irrelevant to this change) error as above. Returning to spire-0.14.1 makes all work.

**Comment by etorreborre** [comment]
Could that be a difference with the exact ScalaCheck version that ends up being used?

**Comment by buzden** [comment]
Well, I started experimenting and realized that

- specs2 4.3.3 works nicely with ScalaCheck 1.14.0 but not with 1.13.5
- specs2 4.3.4 works nicely with ScalaCheck 1.13.5 but not with 1.14.0

(both combinations require spire to be 0.14.1)

**Comment by buzden** [comment]
Well, everything is even more strange. I realized that I have different versions for cats-laws (it was 1.1.0) and cats-core (1.4.0). When I made cats-laws to be 1.4.0 too,

- specs2 4.3.3 started to work with both ScalaCheck 1.13.5 and 1.14.0
- specs2 4.3.4 started to work with ScalaCheck 1.14.0 (becoming failing to work with 1.13.5)

**Comment by etorreborre** [comment]
So in some cases specs2 `4.3.4` works with ScalaCheck `1.14.0` and in some cases it doesn't? Is this something which you could reproduce in a small project? The thing I could do right now if you are blocked is push a `4.3.4-xxx` version which does not support printing the seed when it can't be captured instead of throwing an exception.

**Comment by buzden** [comment]
I feel myself stupid now but I realized that the topic-staring exception is raised only when tests are being run from IntelliJ IDEA. Running using `sbt test` never crashes. And this seems to correlate with the order of entries of the module ([it's a very old bug](https://youtrack.jetbrains.com/issue/SCL-10615)), but I'm not sure enough. This clarifies strange thing of why one combination of versions worked and another didn't.

So, it seems that it is not a direct problem of specs2. I do not understand how (and whether) such exception can be caused by wrong order of libraries. Do you think error message can be improved?

**Comment by terrymunro** [comment]
I don't know if it helps but I'm also seeing this issue. Running in Intellij and running in build tool (though we're using Pants as our build tool)
So is it perhaps something to do with JUnit? I haven't got a simple reproduction yet either. If I can make one I'll post it

**Comment by etorreborre** [comment]
That would be nice if you have a repro, thanks.

**Comment by terrymunro** [comment]
I also feel stupid because I couldn't reproduce then set off to figure out why it wasn't working in my project only to discover I had pinned scalacheck to < 0.14 and forgot to remove that when I upgraded discipline+specs2 to latest.
My apologies for the false alarm. :bowing_man:
