### ISSUE TITLE
Fragments apply method throws stackoverflow with large amounts of fragments

### ISSUE THREAD

**Issue by beaushinkle** [etorreborre/specs2#748]
When running something like:
```
  val fragments = List.range(1, 10000).map(x => ff.text(s"Fragment #$x"))
  Fragments(fragments: _*)
```
it will throw a stackoverflow. Digging in a bit, the underlying `emitSeq` implementation doesn't look like it's tail recursive.

sample project: https://github.com/beaushinkle/specs2-stackoverflow

trace:
```
[error] (run-main-a) java.lang.StackOverflowError
[error] java.lang.StackOverflowError
[error] 	at org.specs2.control.eff.Pure.<init>(Eff.scala:81)
[error] 	at org.specs2.control.eff.EffCreation.pure(Eff.scala:228)
[error] 	at org.specs2.control.eff.EffCreation.pure$(Eff.scala:227)
[error] 	at org.specs2.control.eff.package$all$.pure(package.scala:22)
[error] 	at org.specs2.control.producer.Producers.one(Producer.scala:129)
[error] 	at org.specs2.control.producer.Producers.one$(Producer.scala:128)
[error] 	at org.specs2.control.producer.package$producers$.one(package.scala:13)
[error] 	at org.specs2.control.producer.Producers.emitSeq(Producer.scala:164)
[error] 	at org.specs2.control.producer.Producers.emitSeq$(Producer.scala:161)
[error] 	at org.specs2.control.producer.package$producers$.emitSeq(package.scala:13)
```

Related: this problem happens intermittently in a larger scala project that I wasn't able to reproduce in a minimal setting, but using a fold:

```
      listOfStuff.foldLeft(Fragments(fragmentFactory.start))((fragments, testInfoWithIndex) => {
        val (testInfo, index) = testInfoWithIndex
        fragments ^ br ^ s"${testInfo.name}: ${testInfo.mode}" ! testThing(testInfo.run)
      })
```

**Comment by etorreborre** [comment]
This is now fixed on master. Do you need a release? Otherwise you can also give a bit more stack space to your tests. I tested with `-Xss4M` in `specs2` and it works ok.

**Comment by beaushinkle** [comment]
A release would be very lovely. Thanks a million for the hasty fix!

**Comment by symbiont-eric-torreborre** [comment]
`specs2-4f247eaf0` is now available with the fix.
