### ISSUE TITLE
Ability to run same tests with different environments

### ISSUE THREAD

**Issue by dkomanov** [etorreborre/specs2#827]
I'm trying to rewrite an http service, so what I want is to run same test cases against both services - old and new one, preferably without changing tests itself. The only difference between 2 services is TPC port.

I tried an approach with `map(Fragments)` function, duplicating all fragments and stumbled upon a problem - how to distinguish inside `around`/`aroundContext` method, which service I should call. The only argument in `aroundContext` is of type `Env`. So, I found, that there is a way to change `Env` when I'm doing `map` for fragments. And it works until it doesn't -- test failure reporting doesn't work: exit code is non-zero, but in the report it's marked as successful, which is very inconvenient in development.

I believe that my solution is overly complicated, maybe there is another way? (Also, I would prefer not to run tests twice with different command line arguments as it would complicate CI)

Here is a test case to show problem:
```scala
import java.util.concurrent.atomic.AtomicReference

import org.specs2.execute.{AsResult, Result}
import org.specs2.mutable.SpecificationWithJUnit
import org.specs2.specification.core.{Env, Fragment, Fragments}
import org.specs2.specification.{Around, AroundEach, Context}

class DualTest extends SpecificationWithJUnit with AroundEach {

  sequential

  private var port = 0
  private var prev = 0

  "test" should {
    "succeed" >> {
      // comment line below to make tests failing:
      prev += 1
      port mustEqual prev
    }
  }

  protected override def around[R: AsResult](r: => R): Result = AsResult.effectively(r)

  protected override def aroundContext: Env => Context =
    (env: Env) => {
      new Around {
        override def around[R: AsResult](r: => R) = {
          if (env eq DualTest.service1.get) {
            port = 1
          } else if (env eq DualTest.service2.get) {
            port = 2
          } else {
            port = 0
          }
          DualTest.this.around(r)
        }
      }
    }

  private def fragmentMapper(getter: => AtomicReference[Env]): Fragment => Fragment = {
    case f@Fragment(_, execution, _) if execution.isExecutable =>
      f.updateExecution(_.updateRun(oldRun => env => {
        if (getter.get == null) {
          getter.set(env.copy())
        }
        oldRun(getter.get())
      }))
    case f =>
      f
  }

  override def map(fs: => Fragments) = {
    val ff = fragmentFactory
    import org.specs2.specification.dsl.FragmentsDsl._

    ff.break ^ ff.start ^ ff.text("[service1] ") ^ ff.break ^ ff.tab ^ fs.map(fragmentMapper(DualTest.service1)) ^ ff.end ^
      ff.start ^ ff.text("[service2] ") ^ ff.break ^ ff.tab ^ fs.map(fragmentMapper(DualTest.service2)) ^ ff.end
  }
}

private object DualTest {
  var service1 = new AtomicReference[Env]()
  var service2 = new AtomicReference[Env]()
}
```

Successful report:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='Aggregate Specs2 Test Suite' timestamp='' hostname='localhost' tests='2' failures='0' errors='0' time='0.0' package='' id='0'>
    <properties />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='DualTest' timestamp='' hostname='localhost' tests='2' failures='0' errors='0' time='0.0' package='' id='1'>
    <properties />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='[service1]' timestamp='' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='2'>
    <properties />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='test should' timestamp='' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='3'>
    <properties />
    <testcase name='[service1] ::test should::succeed' classname='DualTest' time='0.0' />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='[service2]' timestamp='' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='4'>
    <properties />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='test should' timestamp='' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='5'>
    <properties />
    <testcase name='[service2] ::test should::succeed' classname='DualTest' time='0.0' />
    <system-out />
    <system-err /></testsuite></testsuites>
```

Failed (broken) report:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='Aggregate Specs2 Test Suite' timestamp='' hostname='localhost' tests='2' failures='0' errors='0' time='0.0' package='' id='0'>
    <properties />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='DualTest' timestamp='' hostname='localhost' tests='2' failures='0' errors='0' time='0.0' package='' id='1'>
    <properties />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='[service1]' timestamp='' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='2'>
    <properties />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='test should' timestamp='' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='3'>
    <properties />
    <testcase name='[service1] ::test should::succeed' classname='DualTest' time='0.0' />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='[service2]' timestamp='' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='4'>
    <properties />
    <system-out />
    <system-err /></testsuite>
  <testsuite name='test should' timestamp='' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='5'>
    <properties />
    <testcase name='[service2] ::test should::succeed' classname='DualTest' time='0.0' />
    <system-out />
    <system-err /></testsuite></testsuites>
```
In console all errors are visible:
```
[info] DualTest
[info] [service1] 
[info] 
[info] 
[info]   test should
.E[error]     x succeed
[error]      1 != 0 (DualTest.scala:20)
[info] 
[info]   [service2] 
[info] 
[info] 
[info]     test should
.E[error]       x succeed
[error]        2 != 0 (DualTest.scala:20)
[info] 
[info] 
[info] 
[info] Total for specification DualTest
[info] Finished in 289 ms
2 examples, 2 failures, 0 error
[info] 

Time: 0.481
There were 2 failures:
1) [service1] ::test should::succeed(com.komanov.junk.dual.DualTest)
java.lang.Exception: 1 != 0
	at com.komanov.junk.dual.DualTest.$anonfun$new$2(DualTest.scala:20)
	at com.komanov.junk.dual.DualTest.around(DualTest.scala:24)
	at com.komanov.junk.dual.DualTest$$anon$1.around(DualTest.scala:37)
	at com.komanov.junk.dual.DualTest$$anon$1.apply(DualTest.scala:28)
2) [service1] ::test should::succeed(com.komanov.junk.dual.DualTest)
java.lang.Exception: 2 != 0
	at com.komanov.junk.dual.DualTest.$anonfun$new$2(DualTest.scala:20)
	at com.komanov.junk.dual.DualTest.around(DualTest.scala:24)
	at com.komanov.junk.dual.DualTest$$anon$1.around(DualTest.scala:37)
	at com.komanov.junk.dual.DualTest$$anon$1.apply(DualTest.scala:28)

FAILURES!!!
Tests run: 2,  Failures: 2
```

**Comment by etorreborre** [comment]
Would that work for you?
```
import org.specs2.mutable.SpecificationWithJUnit
case class ServiceSpec(port: Int) extends SpecificationWithJUnit {
  sequential

  ("test for port "+port) should {
    "succeed" >> {
      ok
    }
  }

}

class ServicesSpec extends SpecificationWithJUnit {
  val service1Spec = ServiceSpec(1)
  val service2Spec = ServiceSpec(2)

  "service 1" >> {
    addFragments(service1Spec.is)
  }

  "service 2" >> {
    addFragments(service2Spec.is)
  }
}
```

**Comment by dkomanov** [comment]
Of course, but I want to refrain from modifying tests (I have quite a lot, hundreds).

**Comment by etorreborre** [comment]
Sorry I missed that part :-)
> preferably without changing tests itself.

Something like that then?
```
import org.specs2.mutable.SpecificationWithJUnit
case class ServiceSpec() extends SpecificationWithJUnit {

  ("testing service on port "+Server.getPort+" should work ok") >> {
    "test 1" >> ok
    "test 2" >> ok
    "test 3" >> ok
  }
}

object Server {
  var port = 0

  def getPort: Int = port
}

class ServicesSpec extends org.specs2.Specification { def is = sequential ^ s2"""
  ${Server.port = 8080; ServiceSpec().is}
  ${Server.port = 9090; ServiceSpec().is}
"""
}
```

**Comment by dkomanov** [comment]
It's kind of the same - currently I have a common base class for all tests. And I would prefer to write some code in one place instead of modifying 100+ files with copy-paste...

**Comment by etorreborre** [comment]
In my example above I don't touch `ServiceSpec`. That spec only accesses `Server.getPort`. How is different in your base specification?

Doesn't something like that work?
```
import org.specs2.mutable.SpecificationWithJUnit

trait BaseSpec extends SpecificationWithJUnit with Server {
  def port: Int = Server.port
}
case class ServiceSpec() extends BaseSpec {

  ("testing service on port "+port+" should work ok") >> {
    "test 1" >> ok
    "test 2" >> ok
    "test 3" >> ok
  }
}

trait Server {
  def port: Int
}
object Server extends Server{
  var port = 0
}

class ServicesSpec extends org.specs2.Specification { def is = sequential ^ s2"""
  ${Server.port = 8080; ServiceSpec().is}
  ${Server.port = 9090; ServiceSpec().is}
"""
}
```

**Comment by dkomanov** [comment]
Now:
```scala
abstract class BaseSpec { def port = 1234 }
class OneOfHundredSpec extends BaseSpec {
  "test something" should { "succeed" >> { ... } }
  "test something else" should { "succeed" >> { ... } }
}
```

I would like to make change like this:
```scala
abstract class BaseSpec { def port = 1234 }
abstract class PolymorphicBaseSpec { def port = portFromSomeVar + additional code }
class OneOfHundredSpec extends PolymorphicBaseSpec {
  // no changes other than extends
  "test something" should { "succeed" >> { ... } }
  "test something else" should { "succeed" >> { ... } }
}
class NotMigratedOfHundredSpec extends BaseSpec {
  "test something" should { "succeed" >> { ... } }
  "test something else" should { "succeed" >> { ... } }
}
```

**Comment by etorreborre** [comment]
Maybe this then
```
import org.specs2.mutable.SpecificationWithJUnit
import org.specs2.specification.core._

trait RunTwiceSpec extends SpecificationWithJUnit with Server {
  def port: Int = Server.port

  override def map(fs: =>Fragments): Fragments =
    step { Server.port = 8080 } ^ fs ^ step { Server.port = 9090} ^ fs
}
case class ServiceSpec() extends RunTwiceSpec {

  ("testing service should work ok") >> {
    "test 1" >> { port.pp; ok }
    "test 2" >> { port.pp; ok }
    "test 3" >> { port.pp; ok }
  }
}

trait Server {
  def port: Int
}
object Server extends Server{
  var port = 0
}
```

If you use the `RunTwiceSpec` trait instead of the `BaseSpec` trait the spec extending that trait will be executed twice with a different port each time. This only shows up because I'm printing the port during the tests though (with `port.pp`) and not when specification is being built.

**Comment by dkomanov** [comment]
It works, but the problem is in IntelliJ test cases are indistinguishable - because of the same name.

**Comment by dkomanov** [comment]
You know what, in this case `mapDescription` actually works!

**Comment by etorreborre** [comment]
Can you please paste the code with `mapDescription` I actually don't see where you use it :-)

**Comment by etorreborre** [comment]
Oh, I see, this seems to be lazy enough to put the right port everywhere!
```
  override def map(fs: =>Fragments): Fragments =
    step { Server.port = 8080 } ^
      fs.mapDescription(d => Text(d.show+" "+Server.port.toString)) ^
      step { Server.port = 9090} ^
      fs.mapDescription(d => Text(d.show+" "+Server.port.toString))
```

**Comment by etorreborre** [comment]
Ok, case closed then?

**Comment by dkomanov** [comment]
Yes, thank you!
